baseURL: "https://www.abozicic.com/"
title: Slow Fetch
paginate: 5
languageCode: en-us
theme: "hugo-PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Slow Fetch
  description: "Blog about web analytics and R programing"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  

  label:
    text: "Slow Fetch"
   

  # home-info mode
  homeInfoParams:
    Title: "Hi there"
    Content: Welcome to my blog, here I write about web analytics and R.

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/aleksa-bo%C5%BEi%C4%8Di%C4%87-ab3397142/"
    - name: email
      url: "mailto:aleksa@scalersppc.com"
    - name: github
      url: "https://github.com/Demiurgos1994"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/Demiurgos1994/blog/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30  
    - identifier: about
      name: About
      url: /about/
      weight: 40    
      
      
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary